# Generated by Django 3.1.3 on 2021-03-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='main.doctor')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='main.member')),
            ],
        ),
    ]
