# Generated by Django 3.1.3 on 2021-03-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_doctorvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.doctor')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_favs', to='main.member')),
            ],
        ),
    ]
