# Generated by Django 3.1.3 on 2021-03-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210328_1543'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorfav',
            unique_together=set(),
        ),
    ]
