# Generated by Django 3.1.3 on 2021-03-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_doctorfav'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorcomment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='doctorfav',
            unique_together={('doctor', 'member')},
        ),
    ]
